### ISSUE TITLE
corriger le poll qui marche mal

### ISSUE THREAD

**Issue by Yourgene** [Yourgene/projetprs#1]
le poll  ne marche pas comme il faut : d'apres maxime il gere mal la file des ACk qui arrivent.

A confirmer par un exemple.

Plan d'action si c'est le cas : 
- remplacer le poll par un select
- ou se documenter sur poll (je prefere ca perso)

**Comment by Maitre-Hiboux** [comment]
https://www.ibm.com/support/knowledgecenter/en/ssw_i5_54/rzab6/poll.htm

watch and learn

**Comment by Yourgene** [comment]
je crois que t'as pas assé watch and learn...
![capture du 2017-06-18 15-44-45](https://user-images.githubusercontent.com/13087999/27261144-15dc0016-543d-11e7-920c-d3553ae4d843.png)

**Comment by Maitre-Hiboux** [comment]
resolved
