### ISSUE TITLE
optimiser le renvoi des segments perdus

### ISSUE THREAD

**Issue by Yourgene** [Yourgene/projetprs#3]
Pour l'instant, si un segment est perdu alors on renvoie tous les segments a partir de ce dernier.
Dans la plupart des cas, il faut juste renvoyer le segment perdu.

Plan d'action : 
- stocker les ~20 derniers segments dans un tableau. Si un segment est perdu, on va le recuperer dans le tableau et on ne renvoie que lui via une sorte d'interruption modélisée sous forme de fonction.

**Comment by Yourgene** [comment]
en lien avec l'issue "client 1 ne restitue pas correctement le fichier", go le lire

**Comment by Maitre-Hiboux** [comment]
a mettre en place : 
- 1 - Créer un tableau d'une trentaine d'éléments contenant de manière glissante les 30 derniers segments envoyés avant de les renvoyer très rapidement (faire un if segperdu < a 30 de seg actuel then sendto le segment)
- 2 - Replacer le fseek après renvoi du paquet perdu à l'endroit ou il était au lieu de renvoyer tout les paquets entre le paquet perdu et le dernier paquet transmis.

**Comment by Yourgene** [comment]
problème réglé dans le commit "le rêve communiste"
