### ISSUE TITLE
le client1 ne restitue pas le document demandé

### ISSUE THREAD

**Issue by Yourgene** [Yourgene/projetprs#8]
il arrive que le client restitue mal le document recu, et pas seulement le dernier segment.

pourquoi ? no sé

**Comment by Yourgene** [comment]
je sais pourquoi.
avec les logs les derniers segments  envoyés sont vides. Parce que lorsqu'un segment est perdu on remet seg a ACK+1, et lors de l'envoi on fait un fread, sauf que avec cette methode : 
1) on ne lit pas la bonne zone du fichier avec le fread
2) on fait avancer la tete de lecture du fread, ce qui fait que les derniers segments ne seront pas envoyés vu qu'on arrivera a la fin du fichier trop rapidement

**Comment by Maitre-Hiboux** [comment]
corrected and tested with 100mio long file.
