### ISSUE TITLE
[A LIRE] pourquoi le serveur est aussi long 

### ISSUE THREAD

**Issue by Yourgene** [Yourgene/projetprs#9]
[logs2.txt](https://github.com/Yourgene/projetprs/files/1082816/logs2.txt)

on voit en ouvrant ces logs que le serveur boucle a MORT pour rien lorsqu'il envoie des segments.

si on enleve cette boucle on sera bon pour avoir de meilleures perfs

**Comment by Maitre-Hiboux** [comment]
seems corrected
